--Este procedimiento comprueba la API Key y el API Secret y si la ip se encuantra autorizada

--ELIMINAMOS EL PROCEDIMIENTO SI EXISTE PARA ACTUALIZAR
IF OBJECTPROPERTY(object_id('dbo.AuthAPI'), N'IsProcedure') = 1
	DROP PROCEDURE [dbo].[AuthAPI]
GO
--CREAMOS EL PROCEDIMIENTO
CREATE PROCEDURE [dbo].[AuthAPI]
    @APIK VARCHAR(MAX),   
    @APIS VARCHAR(MAX),
	@IP VARCHAR(MAX)
AS
	--COMPROBAMOS SI EXISTE UN USUARIO CON LOS PARAMETROS Y SI SU IP SE ENCUENTRA AUTORIZADA
	IF EXISTS(SELECT TOP 1 1 FROM usuarios WHERE apik = @APIK AND apis = @APIS)
	BEGIN
		IF EXISTS(SELECT TOP 1 1 FROM firewall WHERE usuario = (SELECT usuario FROM usuarios WHERE apik = @APIK) AND ip = @IP)
			SELECT Mensaje = '{ code: 0}'--AUTENTICACION CORRECTA CODIGO 0
		ELSE
			SELECT Mensaje = '{ code: 2}' --ERROR POR FALTA DE IP FIREWALL CODIGO 2
	END
	ELSE
	BEGIN
		SELECT Mensaje = '{ code: 1}' --ERROR POR CREDENCIALES INVALIDAS CODIGO 1
	END
GO  
--PROBAMOS EL PROCEDIMIENTO
exec AuthAPI 'A3493LAZ', '$2a$10$Esev9suggnCmG0QPZ6BAZePjJ69xbQfXgVBcOl3xYlaQnanglcK3y', '::1'