CREATE TABLE clientes(
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[url] [varchar](max) NOT NULL,
	[usr] [varchar](max) NOT NULL,
	[psw] [varchar](max) NOT NULL,
	[puertos] [int] NULL,
	[ocupados] [int] NULL,
	[p1] [bit] NULL,
	[p2] [bit] NULL,
	[p3] [bit] NULL,
	[p4] [bit] NULL,
	[p5] [bit] NULL,
	[p6] [bit] NULL,
	[p7] [bit] NULL,
	[p8] [bit] NULL,
	[p9] [bit] NULL,
	[p10] [bit] NULL,
	[p11] [bit] NULL,
	[p12] [bit] NULL,
	[p13] [bit] NULL,
	[p14] [bit] NULL,
	[p15] [bit] NULL,
	[p16] [bit] NULL
)